/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision.gerente;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import controller.DoacaoTableModel;
import controller.EventoTableModel;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import model.Evento;
import model.Doacao;

/**
 *
 * @author Altayr, Klivio Rafael, Francisco Leite
 */
public class GerenciaFinanceira extends javax.swing.JFrame {
    
    /**
     * Creates new form GerenciaFinanceira
     */
    public GerenciaFinanceira() {
        initComponents();
        this.setLocationRelativeTo(null);
        DoacaoTableModel listaDoacao = new DoacaoTableModel();
        EventoTableModel listaEvento = new EventoTableModel();
        ArrayList<Doacao> doacoes;
        ArrayList<Evento> eventos;
        doacoes = listaDoacao.getAll();
        eventos = listaEvento.getAll();
        Float receitaDoacao = 0f;
        Float receitaEvento = 0f;
        Float despesaEvento = 0f;
        Float receitaTotal = 0f;
        String[] receitaDoacoes = new String[doacoes.size()];
        String[] receitaEventos = new String[eventos.size()];
        String[] despesaEventos = new String[eventos.size()];
        String[] receitaCompleta = new String[3];
        
        for(int i=0;i<receitaDoacoes.length;i++){
            if(doacoes.get(i).getMaterial().equals("Dinheiro")){
                receitaDoacoes[i] = doacoes.get(i).getDoador() + ": R$ " + doacoes.get(i).getQuantia();
                receitaDoacao += Float.parseFloat(doacoes.get(i).getQuantia());
            }
        }
        for(int i=0;i<receitaEventos.length;i++){
            receitaEventos[i] = eventos.get(i).getNome() + ": R$ " + eventos.get(i).getMeta();
            receitaEvento += Float.parseFloat(eventos.get(i).getMeta());
        }
        for(int i=0;i<despesaEventos.length;i++){
            despesaEventos[i] = eventos.get(i).getNome() + ": - R$ " + eventos.get(i).getCusto();
            despesaEvento -= Float.parseFloat(eventos.get(i).getCusto());
        }
        
        doacaoReceita.setListData(receitaDoacoes);
        eventoReceita.setListData(receitaEventos);
        eventoDespesa.setListData(despesaEventos);
        txtReceitaDoacao.setText("R$ " +receitaDoacao);
        txtReceitaEvento.setText("R$ " +receitaEvento);
        txtDespesaEvento.setText("R$ " +despesaEvento);
        
        receitaCompleta[0] = ("Receita Doações: R$ " + receitaDoacao);
        receitaCompleta[1] = ("Receita Eventos: R$ " + receitaEvento);
        receitaCompleta[2] = ("Receita Eventos: R$ -" + despesaEvento);
        
        receitaTotal = receitaDoacao+receitaEvento+despesaEvento;
        
        financeiroCompleto.setListData(receitaCompleta);
        
        if(receitaTotal >= 0){
            totalReceita.setText("R$ " + receitaTotal);
        }else if(receitaTotal < 0){
            totalReceita.setText("R$ -"+receitaTotal);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doacaoReceita = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtReceitaDoacao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        eventoReceita = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        txtReceitaEvento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventoDespesa = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        txtDespesaEvento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        financeiroCompleto = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        totalReceita = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerencia Financeira");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Morais Voluntariado - Financeiro");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Receita de Doacoes");

        jScrollPane1.setViewportView(doacaoReceita);

        jLabel3.setText("Total:");

        txtReceitaDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceitaDoacaoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(eventoReceita);

        jLabel4.setText("Total:");

        txtReceitaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceitaEventoActionPerformed(evt);
            }
        });

        jLabel5.setText("Receita de Eventos");

        jScrollPane3.setViewportView(eventoDespesa);

        jLabel6.setText("Total:");

        txtDespesaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDespesaEventoActionPerformed(evt);
            }
        });

        jLabel7.setText("Despesa de Eventos");

        jScrollPane5.setViewportView(financeiroCompleto);

        jLabel10.setText("Total:");

        totalReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalReceitaActionPerformed(evt);
            }
        });

        jLabel11.setText("Receita final do mês");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtReceitaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDespesaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtReceitaDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDespesaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtReceitaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtReceitaDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(totalReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jButton1.setText("Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReceitaDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceitaDoacaoActionPerformed
        
    }//GEN-LAST:event_txtReceitaDoacaoActionPerformed

    private void txtReceitaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceitaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceitaEventoActionPerformed

    private void txtDespesaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDespesaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDespesaEventoActionPerformed

    private void totalReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalReceitaActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        MenuGerente tela = new MenuGerente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DoacaoTableModel listaDoacao = new DoacaoTableModel();
        EventoTableModel listaEvento = new EventoTableModel();
        ArrayList<Doacao> doacoes;
        ArrayList<Evento> eventos;
        doacoes = listaDoacao.getAll();
        eventos = listaEvento.getAll();
        Document document = new Document();
        float custo;
        float saldoEvento = 0;
        float saldoDoacao = 0;
        
        
        try{
            PdfWriter.getInstance(document, new FileOutputStream("Relatório financeiro.pdf"));
            
            
            document.open();
            Paragraph titulo = new Paragraph("MORAIS VOLUNTARIADO\nRelatório Financeiro");
            titulo.setAlignment(Element.ALIGN_CENTER);
            document.add(titulo);
            document.add(new Paragraph("\n\nEVENTOS"));
            for (int i = 0; i< eventos.size(); i++){
                custo = 0;
                document.add(new Paragraph("\n###############################"));
                document.add(new Paragraph("\nEvento: "+eventos.get(i).getNome()));
                document.add(new Paragraph("Pessoa Responsável pelo Evento: " + eventos.get(i).getResponsavel()));
                document.add(new Paragraph("Custo total do Evento: " + eventos.get(i).getCusto()));
                document.add(new Paragraph("Orçamento recebido do Evento: " + eventos.get(i).getMeta()));
                custo -= Float.parseFloat(eventos.get(i).getCusto());
                custo += Float.parseFloat(eventos.get(i).getMeta());
                if(custo>=0){
                    document.add(new Paragraph("Saldo total do Evento: R$ " + custo));
                }else{
                    document.add(new Paragraph("Saldo total do Evento: R$ -" + custo));
                }
                saldoEvento += custo;
                document.add(new Paragraph("\n###############################"));
            }
            document.add(new Paragraph("\n\nDOAÇÕES"));
            for (int i = 0; i< eventos.size(); i++){
                document.add(new Paragraph("\n###############################"));
                document.add(new Paragraph("Doação feita por: " + doacoes.get(i).getDoador()));
                document.add(new Paragraph("Valor doado: " + doacoes.get(i).getQuantia()));
                saldoDoacao += Float.parseFloat(doacoes.get(i).getQuantia());
            }
            
            document.add(new Paragraph("\n\nSALDO TOTAL"));
            if(saldoEvento>=0){
                document.add(new Paragraph("Balanço relacionado a eventos: R$ "+saldoEvento));
            }else{
                document.add(new Paragraph("Balanço relacionado a eventos: R$ -"+saldoEvento));
            }
            document.add(new Paragraph("Balanço relacionado a doações: R$ "+saldoDoacao));
            document.add(new Paragraph("Balanço final: R$ "+(saldoDoacao+saldoEvento)));
        }catch(FileNotFoundException | DocumentException ex) {
            System.out.println("Error"+ex);
        }finally{
            document.close();
        }
        
        try{
            Desktop.getDesktop().open(new File("Relatório Financeiro.pdf"));
            
        }catch (Exception e){
            System.out.println("Error:"+ e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaFinanceira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JList<String> doacaoReceita;
    private javax.swing.JList<String> eventoDespesa;
    private javax.swing.JList<String> eventoReceita;
    private javax.swing.JList<String> financeiroCompleto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField totalReceita;
    private javax.swing.JTextField txtDespesaEvento;
    private javax.swing.JTextField txtReceitaDoacao;
    private javax.swing.JTextField txtReceitaEvento;
    // End of variables declaration//GEN-END:variables
}
