/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision.gerente;

import vision.funcionario.*;
import vision.TelaLogin;
/**
 *
 * @author Altayr
 */
public class MenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        btDoacao = new javax.swing.JButton();
        jTxtMorais = new javax.swing.JLabel();
        btVoluntario = new javax.swing.JButton();
        btEvento = new javax.swing.JButton();
        btFinanceiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerente");
        getContentPane().setLayout(null);

        btSair.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(380, 440, 90, 40);

        btDoacao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btDoacao.setText("Doações");
        btDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btDoacao);
        btDoacao.setBounds(20, 120, 460, 53);

        jTxtMorais.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTxtMorais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMorais.setText("Morais Voluntariado");
        jTxtMorais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jTxtMorais);
        jTxtMorais.setBounds(20, 20, 437, 69);

        btVoluntario.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btVoluntario.setText("Voluntários");
        btVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoluntarioActionPerformed(evt);
            }
        });
        getContentPane().add(btVoluntario);
        btVoluntario.setBounds(20, 200, 460, 53);

        btEvento.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btEvento.setText("Eventos");
        btEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEventoActionPerformed(evt);
            }
        });
        getContentPane().add(btEvento);
        btEvento.setBounds(20, 270, 460, 53);

        btFinanceiro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btFinanceiro.setText("Financeiro");
        btFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(btFinanceiro);
        btFinanceiro.setBounds(20, 350, 460, 53);

        setSize(new java.awt.Dimension(519, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoacaoActionPerformed
        GerenciaDoacoes tela = new GerenciaDoacoes();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btDoacaoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoluntarioActionPerformed
        GerenciaVoluntario tela = new GerenciaVoluntario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoluntarioActionPerformed

    private void btEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEventoActionPerformed
        GerenciaEvento tela = new GerenciaEvento();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btEventoActionPerformed

    private void btFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinanceiroActionPerformed
        GerenciaFinanceira tela = new GerenciaFinanceira();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btFinanceiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDoacao;
    private javax.swing.JButton btEvento;
    private javax.swing.JButton btFinanceiro;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVoluntario;
    private javax.swing.JLabel jTxtMorais;
    // End of variables declaration//GEN-END:variables
}
