/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import javax.swing.JOptionPane;
import vision.funcionario.MenuFuncionario;
import vision.voluntario.MenuVoluntario;
import vision.gerente.MenuGerente;

/**
 *
 * @author Altayr
 */
public class TelaLogin extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaLogin
     */
    
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public boolean loginFuncionario(String login, String senha) {        
        return login.equals("funcionario") && senha.equals("123");
    }
    
    public boolean loginUsuario(String login, String senha) {
        return login.equals("voluntario") && senha.equals("456");        
    
    }
    
    public boolean loginGerente(String login, String senha){
        return login.equals("gerente") && senha.equals("789");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtLogin = new javax.swing.JButton();
        jLUsuario = new javax.swing.JLabel();
        jLLogin = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jTxtLogin = new javax.swing.JTextField();
        jTxtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jBtLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtLogin.setText("Entrar");
        jBtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLoginActionPerformed(evt);
            }
        });

        jLUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLUsuario.setText("Usuário");

        jLLogin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLLogin.setText("LOGIN");

        jLSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSenha.setText("Senha");

        jTxtLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLoginActionPerformed(evt);
            }
        });

        jTxtSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLLogin)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSenha)
                    .addComponent(jLUsuario))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jBtLogin)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLLogin)
                .addGap(36, 36, 36)
                .addComponent(jLUsuario)
                .addGap(18, 18, 18)
                .addComponent(jTxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLSenha)
                .addGap(16, 16, 16)
                .addComponent(jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jBtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLoginActionPerformed
        // TODO add your handling code here:
        if(jTxtLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"POR FAVOR \n digite o usuario","ERRO USUÁRIO",3);
            return;
        }
        if(jTxtSenha.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null,"POR FAVOR \n digite a senha","ERRO SENHA",3);
        }
        if(this.loginFuncionario(jTxtLogin.getText(), new String(jTxtSenha.getPassword()))){

            JOptionPane.showMessageDialog(null,"SEJA BEM VINDO\n FUNCIONARIO");
            MenuFuncionario telaPrincipal = new MenuFuncionario();
            telaPrincipal.setVisible(true);
            dispose();
        }
        else if (this.loginUsuario(jTxtLogin.getText(), new String(jTxtSenha.getPassword()))){
            
            JOptionPane.showMessageDialog(null,"SEJA BEM VINDO\n VOLUNTARIO");
            MenuVoluntario telaPrincipal = new MenuVoluntario();
            telaPrincipal.setVisible(true);
            dispose();
        }
        else if (this.loginGerente(jTxtLogin.getText(), new String(jTxtSenha.getPassword()))){
            
            JOptionPane.showMessageDialog(null,"SEJA BEM VINDO\n GERENTE");
            MenuGerente telaPrincipal = new MenuGerente();
            telaPrincipal.setVisible(true);
            dispose();
        }
        
//                if(this.loginUsuario(txtLogin.getText(), new String(txtSenha.getPassword()))) {
//            
//                        Icon loginCertoUsuario = new ImageIcon(getClass().getResource("/iconMensagem/pin-ok-32.png"));
//                        JOptionPane.showMessageDialog(null,"SEJA BEM VINDO\n USUÁRIO","USUÁRIO",JOptionPane.INFORMATION_MESSAGE,loginCertoUsuario);
//                        TelaPrincipalUsuario telaPrincipal = new TelaPrincipalUsuario();
//                        telaPrincipal.setVisible(true);
//                        dispose();
//                    }
        else {
            JOptionPane.showMessageDialog(null,"SENHA OU LOGIN INVÁLIDO");

        }
    }//GEN-LAST:event_jBtLoginActionPerformed

    private void jTxtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtLogin;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JTextField jTxtLogin;
    private javax.swing.JPasswordField jTxtSenha;
    // End of variables declaration//GEN-END:variables
}
