/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision.voluntario;
import controller.DoacaoTableModel;
import javax.swing.JOptionPane;
import model.Doacao;

/**
 *
 * @author Altayr
 */
public class RealizarDoacao extends javax.swing.JFrame {
    
    DoacaoTableModel tableModel = new DoacaoTableModel();
    final int SIM = 0;
    final int NAO = 1;
    final int CANCELAR = 2;

    /**
     * Creates new form GerenciaDoacoes
     */
    public RealizarDoacao() {
        initComponents();
        
        jTDoacao.setModel(tableModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDoacao = new javax.swing.JTable();
        jLDoador = new javax.swing.JLabel();
        jTxtDoador = new javax.swing.JTextField();
        jLDataDoacao = new javax.swing.JLabel();
        jTxtDataDoacao = new javax.swing.JFormattedTextField();
        jMaterialDoacao = new javax.swing.JLabel();
        jTxtMaterialDoacao = new javax.swing.JTextField();
        jLQuantia = new javax.swing.JLabel();
        jTxtQuantia = new javax.swing.JTextField();
        jMetodoEntrega = new javax.swing.JLabel();
        jLRecorrente = new javax.swing.JLabel();
        jRecorrente = new javax.swing.JCheckBox();
        jBoxMetodoEntrega = new javax.swing.JComboBox<>();
        jBtSalvar = new javax.swing.JButton();
        jBtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doações");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Morais Voluntariado - Doações");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTDoacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTDoacao);

        jLDoador.setText("Doador:");

        jTxtDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDoadorActionPerformed(evt);
            }
        });

        jLDataDoacao.setText("Data da Doação:");

        try {
            jTxtDataDoacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jMaterialDoacao.setText("Material da  Doação:");

        jTxtMaterialDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMaterialDoacaoActionPerformed(evt);
            }
        });

        jLQuantia.setText("Quantia:");

        jTxtQuantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantiaActionPerformed(evt);
            }
        });

        jMetodoEntrega.setText("Método de Entrega:");

        jLRecorrente.setText("Recorrente:");

        jBoxMetodoEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o método", "Local", "Coleta" }));

        jBtSalvar.setText("Doar");
        jBtSalvar.setAlignmentY(0.0F);
        jBtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtSalvar.setVerifyInputWhenFocusTarget(false);
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });

        jBtVoltar.setText("Voltar");
        jBtVoltar.setAlignmentY(0.0F);
        jBtVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtVoltar.setVerifyInputWhenFocusTarget(false);
        jBtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtSalvar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLDataDoacao)
                                    .addComponent(jLDoador))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtDoador)
                                    .addComponent(jTxtDataDoacao, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jMaterialDoacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxtMaterialDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLQuantia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxtQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jMetodoEntrega)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBoxMetodoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLRecorrente)
                                        .addGap(10, 10, 10)
                                        .addComponent(jRecorrente)))))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLDoador)
                                .addComponent(jTxtDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLDataDoacao)
                                .addComponent(jTxtDataDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jMaterialDoacao)
                                .addComponent(jTxtMaterialDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLQuantia)
                                .addComponent(jTxtQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMetodoEntrega)
                            .addComponent(jBoxMetodoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRecorrente)
                            .addComponent(jRecorrente))))
                .addGap(9, 9, 9)
                .addComponent(jBtSalvar)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtVoltar)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDoadorActionPerformed

    private void jTxtMaterialDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMaterialDoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMaterialDoacaoActionPerformed

    private void jTxtQuantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantiaActionPerformed

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
        String doador = jTxtDoador.getText();
        String dataDoacao = jTxtDataDoacao.getText();
        String materialDoacao = jTxtMaterialDoacao.getText();
        Float quantia = Float.parseFloat(jTxtQuantia.getText());
        String metodoEntrega = (String) jBoxMetodoEntrega.getSelectedItem();
        boolean recorrente = jRecorrente.isSelected();
        
        Doacao d = new Doacao(doador, dataDoacao, materialDoacao, quantia, metodoEntrega, recorrente);
        
        tableModel.addRow(d);
        
        JOptionPane.showMessageDialog(null, "Doação registrada com sucesso!");
        jTxtDoador.setText("");
        jTxtDataDoacao.setText("");
        jTxtMaterialDoacao.setText("");
        jTxtQuantia.setText("");
        jBoxMetodoEntrega.setSelectedIndex(0);
        jRecorrente.setSelected(false);
        
        
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jBtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVoltarActionPerformed
        MenuVoluntario tela = new MenuVoluntario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarDoacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxMetodoEntrega;
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JButton jBtVoltar;
    private javax.swing.JLabel jLDataDoacao;
    private javax.swing.JLabel jLDoador;
    private javax.swing.JLabel jLQuantia;
    private javax.swing.JLabel jLRecorrente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMaterialDoacao;
    private javax.swing.JLabel jMetodoEntrega;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jRecorrente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDoacao;
    private javax.swing.JFormattedTextField jTxtDataDoacao;
    private javax.swing.JTextField jTxtDoador;
    private javax.swing.JTextField jTxtMaterialDoacao;
    private javax.swing.JTextField jTxtQuantia;
    // End of variables declaration//GEN-END:variables
}
